### ISSUE TITLE
branch on delete trigger is wrong (always main)

### ISSUE THREAD

**Issue by dennistruemper** [gacts/github-slug#49]
Hi @tarampampam ,

I just tried this action on a delete trigger like this:

```yaml
name: trigger on delete

on: [delete]
jobs:
  clean:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'


    steps:
      - uses: actions/checkout@v2
      - uses: gacts/github-slug@v1
        id: slug
        with:
          to-slug: ${{ github.event.ref }}
      - ...
```

And this is the output I got ( just the branch entries):
```
Run gacts/github-slug@v1
Setup action

│ is-branch         │ The workflow was triggered on a branch │ ${{ steps.slug.outputs.is-branch }}         │ true                            │
│ is-tag            │ The workflow was triggered on a tag    │ ${{ steps.slug.outputs.is-tag }}            │ false                                    │
│ branch-name       │ Current branch name                    │ ${{ steps.slug.outputs.branch-name }}       │ main                             │
│ branch-name-slug  │ A slugged version of "branch-name"     │ ${{ steps.slug.outputs.branch-name-slug }}  │ main              │
│ slug              │ A slugged version of "to-slug" input   │ ${{ steps.slug.outputs.slug }}              │ f-gh-actions                           │
```

As you can see, the github.event.ref has the deleted brach name slug. But the default branch name is main. This is not what I expected.

Have a nice weekend,
Dennis
