### ISSUE TITLE
pull_request `closed` is not a branch

### ISSUE THREAD

**Issue by boredland** [gacts/github-slug#58]
I have an action listening to PR close events:

```yaml
on:
  pull_request:
    types:
      - closed
```

sadly this action reports the commit short-sha as branch:

```
│ is-branch         │ The workflow was triggered on a branch │ ${{ steps.slug.outputs.is-branch }}         │ false                                    │
├───────────────────┼────────────────────────────────────────┼─────────────────────────────────────────────┼──────────────────────────────────────────┤
```

would you agree that it should slugify the `${{ github.head_ref }}`?

**Comment by tarampampam** [comment]
Hi @boredland! Is there any example action log with this event?

**Comment by tarampampam** [comment]
I could watch the complete log and your CI scenario if this is possible

**Comment by tarampampam** [comment]
I can't reproduce the behavior, described by you :(

https://github.com/gacts/github-slug/actions/runs/4733465998/jobs/8401036329#step:3:11

Sandbox: https://github.com/gacts/github-slug/pull/59

![image](https://user-images.githubusercontent.com/7326800/232808380-98467362-7384-4fe5-b986-9c6cd614502a.png)

```yaml
name: TEST_ISSUE

on:
  pull_request:
    types:
      - closed

jobs:
  run-this-action:
    name: Run action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run this action
        uses: ./
        id: slug
```
